//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCCPereira.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATION_PAYDAD
    {
        public int ID { get; set; }
        public string USER_API { get; set; }
        public string PASSWORD_API { get; set; }
        public string USER { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ID_SESSION { get; set; }
        public Nullable<int> ID_PAYPAD { get; set; }
        public Nullable<int> ID_SITE { get; set; }
        public string TOKEN_API { get; set; }
        public Nullable<int> TYPE { get; set; }
    }
}
