//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCCPereira.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayPlusLocalBDEntities : DbContext
    {
        public PayPlusLocalBDEntities()
            : base("name=PayPlusLocalBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONFIGURATION_PAYDAD> CONFIGURATION_PAYDAD { get; set; }
        public virtual DbSet<DEVICE_LOG> DEVICE_LOG { get; set; }
        public virtual DbSet<ERROR_LOG> ERROR_LOG { get; set; }
        public virtual DbSet<PAYPAD_CONSOLE_ERROR> PAYPAD_CONSOLE_ERROR { get; set; }
        public virtual DbSet<PAYPAD_LOG> PAYPAD_LOG { get; set; }
        public virtual DbSet<TRANSACTION_DESCRIPTION> TRANSACTION_DESCRIPTION { get; set; }
        public virtual DbSet<TRANSACTION_DETAIL> TRANSACTION_DETAIL { get; set; }
        public virtual DbSet<TRANSACTION_ERROR_SERVICE> TRANSACTION_ERROR_SERVICE { get; set; }
        public virtual DbSet<PAYER> PAYER { get; set; }
        public virtual DbSet<TRANSACTION> TRANSACTION { get; set; }
    }
}
