//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCCPereira.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION_ERROR_SERVICE
    {
        public int TRANSACTION_ERROR_SERVICE_ID { get; set; }
        public string JSON { get; set; }
        public int TRANSACTION_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public int STATE { get; set; }
        public Nullable<int> NOTIFICATION_INTENT { get; set; }
    }
}
