//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFCCPereira.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImagesUrlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImagesUrlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFCCPereira.Resources.ImagesUrlResource", typeof(ImagesUrlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Backgrounds/bg-alert-blanck.png.
        /// </summary>
        internal static string AlertBlanck {
            get {
                return ResourceManager.GetString("AlertBlanck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Backgrounds/bg-alert-error.png.
        /// </summary>
        internal static string AlertError {
            get {
                return ResourceManager.GetString("AlertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images/Backgrounds/bg-alert-info.png.
        /// </summary>
        internal static string AlertInfo {
            get {
                return ResourceManager.GetString("AlertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Backgrounds/bg-consult.png.
        /// </summary>
        internal static string BackgroundConsult {
            get {
                return ResourceManager.GetString("BackgroundConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Backgrounds/bg-consult-name.png.
        /// </summary>
        internal static string BackgroundConsultName {
            get {
                return ResourceManager.GetString("BackgroundConsultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Backgrounds/bg-consult-transact.png.
        /// </summary>
        internal static string BackgroundConsultTransact {
            get {
                return ResourceManager.GetString("BackgroundConsultTransact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Backgrounds/bg-menu-payment.jpg.
        /// </summary>
        internal static string BackgroundSubmenuPayment {
            get {
                return ResourceManager.GetString("BackgroundSubmenuPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Backgrounds/bg-menu-withdrawal.jpg.
        /// </summary>
        internal static string BackgroundSubmenuWithdrawal {
            get {
                return ResourceManager.GetString("BackgroundSubmenuWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Buttons/btn-consign.png.
        /// </summary>
        internal static string BtnConsign {
            get {
                return ResourceManager.GetString("BtnConsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Buttons/btn-pay.png.
        /// </summary>
        internal static string BtnPay {
            get {
                return ResourceManager.GetString("BtnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/Buttons/btn-withdraw.png.
        /// </summary>
        internal static string BtnWithdraw {
            get {
                return ResourceManager.GetString("BtnWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/rbtn-id.png.
        /// </summary>
        internal static string ImageCheckId {
            get {
                return ResourceManager.GetString("ImageCheckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/rbtn-name.png.
        /// </summary>
        internal static string ImageCheckName {
            get {
                return ResourceManager.GetString("ImageCheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/rbtn-radicate.png.
        /// </summary>
        internal static string ImageCheckRadicate {
            get {
                return ResourceManager.GetString("ImageCheckRadicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/rbtn-receipt.png.
        /// </summary>
        internal static string ImageCheckReceipt {
            get {
                return ResourceManager.GetString("ImageCheckReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/no-check.png.
        /// </summary>
        internal static string ImageOnSelectOption {
            get {
                return ResourceManager.GetString("ImageOnSelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/ok.png.
        /// </summary>
        internal static string ImageSelectOption {
            get {
                return ResourceManager.GetString("ImageSelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/img-cancel.png.
        /// </summary>
        internal static string ImgCancel {
            get {
                return ResourceManager.GetString("ImgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Others/img-active.png.
        /// </summary>
        internal static string ImgSelect {
            get {
                return ResourceManager.GetString("ImgSelect", resourceCulture);
            }
        }
    }
}
